export const ordersListData = [
    {
      id: 1,
      name: "Jondo",
      price: "$112",
      number: "01575699193",
      payment: "Paid",
      email: "mostafizar@gmail.com",
    },
    {
      id: 2,
      name: "Mostafizur",
      price: "$15",
      number: "01575699193",
      payment: "Due",
      email: "mofiz@gmail.com",
    },
    {
      id: 3,
      name: "Ali",
      price: "$112",
      number: "01575699193",
      payment: "Paid",
      email: "mofiz@gmail.com",
    },
    {
      id: 4,
      name: "Surove",
      price: "$500",
      number: "01575699193",
      payment: "Paid",
      email: "mofiz@gmail.com",
    },
    {
      id: 5,
      name: "Will Fan",
      price: "$30",
      number: "01575699193",
      payment: "Due",
      email: "mofiz@gmail.com",
    },
    {
      id: 6,
      name: "Jondo",
      price: "$112",
      number: "01575699193",
      payment: "Paid",
      email: "mostafizar@gmail.com",
    },
    {
      id: 7,
      name: "Kritick",
      price: "$112",
      number: "01575699193",
      payment: "Paid",
      email: "mofiz@gmail.com",
    },
    {
      id: 8,
      name: "Kritick",
      price: "$112",
      number: "01575699193",
      payment: "Paid",
      email: "mofiz@gmail.com",
    },
    {
      id: 9,
      name: "Kritick",
      price: "$112",
      number: "01575699193",
      payment: "Paid",
      email: "mofiz@gmail.com",
    },
    {
      id: 10,
      name: "Kritick",
      price: "$112",
      number: "01575699193",
      payment: "Paid",
      email: "mofiz@gmail.com",
    },
    {
      id: 11,
      name: "Kritick",
      price: "$112",
      number: "01575699193",
      payment: "Paid",
      email: "mofiz@gmail.com",
    },
    {
      id: 12,
      name: "Kritick",
      price: "$112",
      number: "01575699193",
      payment: "Paid",
      email: "mofiz@gmail.com",
    },
    {
      id: 13,
      name: "Kritick",
      price: "$112",
      number: "01575699193",
      payment: "Paid",
      email: "mofiz@gmail.com",
    },
    {
      id: 14,
      name: "Kritick",
      price: "$112",
      number: "01575699193",
      payment: "Paid",
      email: "mofiz@gmail.com",
    },
  ];